import { Player } from '@remotion/player';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { MyComposition } from '../remotion/MyComposition';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <span className="text-red-500">Welcome</span> to{' '}
          <a href="https://nextjs.org">Next.js</a>
        </h1>
        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>
        {/* I've added a dashed red border so we can see the edges of the video. */}
        <div className="border-2 border-dashed border-red-500">
          <Player
            style={{
              // The remotion player will resize to fit inside the player.
              // We set a fixed width and the height will be automatically adjusted for you.
              width: 640,
            }}
            component={MyComposition}
            durationInFrames={120}
            compositionWidth={1920}
            compositionHeight={1080}
            fps={30}
            loop
            autoPlay
            controls
          />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
